### ISSUE TITLE
Bullet Physics SDK

### ISSUE THREAD

**Issue by johanhenriksson** [johanhenriksson/goworld#20]
Attempt to use Bullet Physics SDK as the underlying physics engine.

The first step would be to create a go wrapper, check out https://github.com/fcvarela/gosg/blob/master/physics/bullet/physicssystem.go for inspiration

**Comment by einthusan** [comment]
Wow, just wanted to say great work man! Keep it up, and I hope you will be working on this more actively. It looks fantastic!

**Comment by johanhenriksson** [comment]
Thank you! I'm working on it in bursts every now and then, but sadly I don't have a ton of time right now. I also don't really have anything that I would like to use the engine for yet, I primarily built it for fun. The voxel/minecraft looking thing is mostly to have something interesting to render and to test with.

Contributions would be welcome if you are interested :) The OpenGL ES idea would be really cool!

**Comment by einthusan** [comment]
Hey, I am interested in funding this project, but would you be able to purely isolate the different systems so that others can learn from them? And would you be able to make some proper documentation (including diagrams) on how the different layers of code and architecture of this system works?

**Comment by johanhenriksson** [comment]
I suppose all of that could be done. After such a long time tinkering with it I'm quite happy with the architecture and I think it should be reasonably easy to understand as far as 3D engines go. 

That said I'm quite deeply involved in a bunch of other work that I cant easily step away from, but I'm curious about your interest in the project and would be open to talk more about it. You can email me at github username at live dot com.

**Comment by einthusan** [comment]
I've sent you an email. Cheers!
